version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: video-backend
    ports:
      - "10000:10000"
      - "5678:5678"
    volumes:
      - ${ANALYSIS_HOME_DIR}/backend:/app
      - ${ANALYSIS_HOME_DIR}/uploads:/uploads
      - ${ANALYSIS_HOME_DIR}/models:/models
      - ${AIVANAS_SVR_DIR}:/aivanas
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: "4gb"
    env_file:
      - .env
    restart: always
    command:
      [
        "python",
        "-m",
        "debugpy",
        "--listen",
        "0.0.0.0:5678",
        "--wait-for-client",
        "main.py",
      ]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder
    container_name: video-frontend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ${ANALYSIS_HOME_DIR}/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    shm_size: "4gb"
    env_file:
      - .env
    restart: always
